version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

