version: 2
jobs:
  build:
    docker:
      - image: switchbitcom/winch:golang
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /go/src/github.com/switch-bit/orlop
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Turn the handle
          command: winch ci
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: DockerHubUpdater
